# base image for container
FROM ubuntu:latest

# updates APT
RUN apt-get update

# upgrades currently installed software
RUN apt-get upgrade -y

# echoes “Hello, World!” on terminal
CMD [ "echo", "Hello, World!" ]
